### ISSUE TITLE
Program stops responding at collisions with trace display enabled

### ISSUE THREAD

**Issue by giulioforesto** [giulioforesto/planets#42]
Example file: collisions1.txt.

Error message example: `JSONObject["0068"] not found.` (planets.pde l. 172)

**Comment by gabrielfougeron** [comment]
Is it linked with collision ?

**Comment by giulioforesto** [comment]
It only happens with files with collisions but indeed, I haven't checked if
it happens exactly at a step with collision or at any step of the file.
Anyway it is a trace issue.
Le 6 janv. 2015 08:37, "gabrielfougeron" <notifications@github.com> a écrit
:
